In [1]:
import pandas as pd

In [5]:
equipment_df = pd.read_csv('../../../data/cell_manager/equipment.csv')

In [6]:
equipment_df.shape

(177986, 16)

In [11]:
equipment_df.head(20)

,2000024892,2000024893,2000024894,2000024895,2000024898,2000024899,2000024900,2000026099,2000026100,2000026101,2000026102,2000026103,2000026104,2000039933,2000053806,2000053552
0,10.0,11.0,28.0,6.0,20.0,22.0,8.0,1844000.0,1950480.0,5726.0,115401.0,2380.0,113310.0,5.70,25.0,NaN
1,8.0,8.0,27.0,NaN,18.0,22.0,8.0,1804800.0,1036800.0,2820.0,27896.0,NaN,25318.0,NaN,0.0,NaN
2,11.0,11.0,27.0,3.0,21.0,22.0,8.0,1843200.0,2293920.0,3744.0,113858.0,878.0,109953.0,5.88,4.0,NaN
3,11.0,10.0,26.0,5.0,19.0,21.0,8.0,1709000.0,2322000.0,3788.0,56064.0,1999.0,52658.0,5.84,11.0,NaN
4,11.0,11.0,28.0,NaN,20.0,23.0,8.0,2000000.0,2304720.0,5618.0,116162.0,NaN,112691.0,NaN,0.0,NaN
5,8.0,8.0,23.0,4.0,18.0,12.0,8.0,1401000.0,921600.0,2835.0,28143.0,1299.0,25633.0,5.20,24.0,NaN
6,11.0,11.0,28.0,7.0,20.0,22.0,8.0,1843200.0,2377080.0,5703.0,114553.0,2698.0,110384.0,6.01,15.0,NaN
7,11.0,12.0,28.0,0.0,21.0,22.0,8.0,1766400.0,2253960.0,7638.0,233695.0,0.0,230925.0,0.00,16.0,NaN
8,8.0,10.0,28.0,4.0,20.0,21.0,8.0,1709000.0,978480.0,3784.0,116388.0,1309.0,113078.0,5.93,20.0,NaN
9,11.0,10.0,28.0,9.0,19.0,22.0,8.0,1844000.0,2073600.0,3689.0,56182.0,3899.0,53970.0,5.90,15.0,NaN
10,5.0,6.0,22.0,3.0,15.0,11.0,4.0,1209600.0,518400.0,1905.0,13974.0,998.0,10998.0,5.00,35.0,NaN
11,11.0,9.0,27.0,0.0,19.0,22.0,8.0,1804800.0,2229120.0,3473.0,55347.0,0.0,51443.0,0.00,10.0,NaN
12,11.0,10.0,26.0,4.0,19.0,21.0,8.0,1709000.0,2201040.0,3789.0,56806.0,1299.0,53842.0,5.93,17.0,NaN
13,8.0,9.0,27.0,4.0,19.0,22.0,8.0,1804800.0,1094400.0,3569.0,56092.0,1500.0,52231.0,6.20,4.0,NaN
14,11.0,10.0,27.0,7.0,19.0,22.0,8.0,1843200.0,2073600.0,3740.0,56479.0,2999.0,53113.0,6.01,23.0,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,11.0,10.0,28.0,7.0,20.0,22.0,8.0,1785600.0,4210560.0,NaN,111751.0,NaN,108387.0,NaN,42.0,NaN
17,11.0,12.0,27.0,5.0,20.0,21.0,8.0,1708800.0,2527200.0,7623.0,115759.0,1799.0,111105.0,6.40,12.0,NaN
18,11.0,12.0,28.0,8.0,21.0,22.0,8.0,1766400.0,2203200.0,7638.0,236946.0,3299.0,233970.0,5.99,13.0,NaN
19,8.0,8.0,22.0,4.0,15.0,17.0,8.0,1508000.0,921600.0,2761.0,14035.0,1399.0,10459.0,5.50,34.0,NaN

In [8]:
equipment_df.describe()

,2000024892,2000024893,2000024894,2000024895,2000024898,2000024899,2000024900,2000026099,2000026100,2000026101,2000026102,2000026103,2000026104,2000039933,2000053806,2000053552
count,141041.000000,138651.000000,141048.000000,128031.000000,143689.000000,140524.000000,143696.000000,1.402210e+05,1.410430e+05,1.356900e+05,141037.000000,122547.000000,140985.000000,122765.000000,147387.000000,5998.0
mean,10.375508,10.048056,26.103653,5.160492,19.010105,20.511614,7.722477,1.781494e+06,2.065701e+06,1.410142e+04,81500.020470,2016.070504,78150.073263,5.092862,17.293927,1.0
std,1.356180,1.998887,2.435220,2.815432,1.970089,3.719115,1.213554,2.268975e+05,5.726266e+05,2.399705e+05,48970.080326,1359.322949,48502.257635,1.984209,12.625119,0.0
min,1.000000,0.000000,15.000000,0.000000,2.000000,0.000000,1.000000,7.920000e+05,5.760000e+04,0.000000e+00,670.000000,0.000000,0.000000,0.000000,0.000000,1.0
25%,11.000000,10.000000,25.000000,4.000000,19.000000,21.000000,8.000000,1.708800e+06,2.073600e+06,3.598000e+03,56182.000000,1198.000000,52183.000000,5.500000,7.000000,1.0
50%,11.000000,10.000000,27.000000,5.000000,19.000000,22.000000,8.000000,1.805000e+06,2.196720e+06,3.854000e+03,57695.000000,1998.000000,54985.000000,5.800000,15.000000,1.0
75%,11.000000,11.000000,28.000000,7.000000,20.000000,22.000000,8.000000,1.844000e+06,2.371680e+06,5.714000e+03,115561.000000,2900.000000,111474.000000,6.010000,25.000000,1.0
max,11.000000,14.000000,29.000000,12.000000,23.000000,24.000000,10.000000,3.900000e+06,4.492800e+06,7.924276e+06,965790.000000,16999.000000,960679.000000,10.100000,606.000000,1.0

In [12]:
equipment_df['2000024895'].unique()

array([ 6., nan,  3.,  5.,  4.,  7.,  0.,  9.,  8., 11.,  2., 12., 10.])

In [13]:
equipment_df['2000024892'].unique()

array([10.,  8., 11.,  5., nan,  6.,  9.,  4.,  2.,  3.,  1.])

In [14]:
equipment_df['2000024893'].unique()

array([11.,  8., 10., 12.,  6.,  9., nan, 13.,  0.,  4., 14.,  7.,  5.,
        3.,  2.])

In [15]:
equipment_df['2000026104'].unique()

array([113310.,  25318., 109953., ...,  11052.,  61437.,   4023.])

In [16]:
equipment_df['2000039933'].unique()

array([ 5.7 ,   nan,  5.88,  5.84,  5.2 ,  6.01,  0.  ,  5.93,  5.9 ,
        5.  ,  6.2 ,  6.4 ,  5.99,  5.5 ,  6.43,  5.15,  6.28,  6.26,
        6.59,  5.8 ,  6.09,  6.3 ,  6.42,  5.1 ,  3.5 ,  5.65,  6.5 ,
        6.  ,  6.39,  5.46,  6.53,  6.44,  4.7 ,  7.12,  5.85,  5.25,
        5.3 ,  7.2 ,  5.43,  6.1 ,  6.22,  6.18,  6.41,  6.17,  6.21,
        4.5 ,  6.15,  4.  ,  6.9 ,  4.2 ,  6.6 ,  5.45,  7.  ,  6.7 ,
        6.8 ,  5.98,  5.36,  4.3 ,  8.  ,  5.95,  5.09,  5.96,  3.3 ,
        6.33,  2.8 ,  5.86,  3.9 ,  4.8 ,  1.8 ,  3.7 ,  4.95, 10.1 ,
        8.4 ,  2.4 ,  3.97,  3.95,  3.  ,  3.65,  1.3 ,  3.8 ,  4.52,
        4.99,  4.4 ,  4.66,  5.73,  3.2 ,  5.6 ,  4.6 ,  4.19,  4.65,
        2.55,  7.02,  3.67,  1.77])

In [17]:
equipment_df['2000053806'].unique()

array([ 25.,   0.,   4.,  11.,  24.,  15.,  16.,  20.,  35.,  10.,  17.,
        23.,  nan,  42.,  12.,  13.,  34.,  22.,   3.,  28.,   8.,   9.,
        32.,   1.,  48.,   6.,  27.,  21.,  37.,   7.,  19.,  29.,  18.,
         2.,  33.,  26.,   5.,  38.,  14.,  56.,  40.,  43.,  51.,  31.,
        36.,  52.,  49.,  30.,  44.,  41.,  59.,  54.,  60.,  50.,  47.,
        46.,  85.,  45.,  39.,  77.,  61.,  62.,  53.,  68.,  58.,  55.,
        81.,  74.,  78.,  71.,  72.,  63.,  57.,  76.,  75.,  67.,  66.,
        69.,  73.,  79.,  65.,  70., 605.,  64.,  88.,  86.,  80.,  90.,
        83.,  82.,  87.,  95., 606.,  84.])

In [191]:
id_mean_df = pd.read_csv('../../../data/cell_manager/ID_meaning_v5.csv')

In [192]:
id_mean_df.head(20)

      tag_code tag_type1 tag_type2     tag_desc Unnamed: 4
0       610120       NaN       NaN         风控分1        NaN
1     61012004       NaN       NaN         风控分2        NaN
2     61012005       NaN       NaN        场景质量分        NaN
3     61012020       NaN       NaN    场景1的催收难度分        NaN
4     61012021       NaN       NaN    场景2的催收难度分        NaN
5   2000000134       NaN      人口属性         年龄分段        NaN
6   2000000136       NaN      人口属性           性别        NaN
7   2000019444       NaN        健康           健康        NaN
8   2000019464       NaN       NaN           工具        NaN
9   2000019469       NaN        理财         金融理财        NaN
10  2000019493       NaN        理财           彩票        NaN
11  2000021475       NaN        消费         京东标签        NaN
12  2000024892       NaN      设备属性        分辨率离散        NaN
13  2000024893       NaN      设备属性      ram大小离散        NaN
14  2000024894       NaN      设备属性    api_level        NaN
15  2000024895       NaN      设备属性  machine价格离散        NaN
16  2000024897       NaN      设备属性        brand        NaN
17  2000024898       NaN      设备属性        rom离散        NaN
18  2000024899       NaN      设备属性      cpu频率离散        NaN
19  2000024900       NaN      设备属性      cpu核数离散        NaN

In [193]:
id_mean_df = id_mean_df.fillna("NaN")

In [194]:
id_mean_df.head()

   tag_code tag_type1 tag_type2   tag_desc Unnamed: 4
0    610120       NaN       NaN       风控分1        NaN
1  61012004       NaN       NaN       风控分2        NaN
2  61012005       NaN       NaN      场景质量分        NaN
3  61012020       NaN       NaN  场景1的催收难度分        NaN
4  61012021       NaN       NaN  场景2的催收难度分        NaN

In [195]:
def get_id2info_dicts(id_mean_df):
    """
    Get mapping from tag ids to tag type and from tag ids to tag description 
    """
    id2desc_dict = dict()
    id2type1_dict = dict()
    id2type2_dict = dict()
    for index, row in id_mean_df.iterrows():
    #     print(type(row['tag_code']), row['tag_type'], row['tag_desc'])
        id2type1_dict[str(row['tag_code'])] = row['tag_type1']
        id2type2_dict[str(row['tag_code'])] = row['tag_type2']
        id2desc_dict[str(row['tag_code'])] = row['tag_desc']
    return id2desc_dict, id2type1_dict, id2type2_dict

In [196]:
id2desc_dict, id2type1_dict, id2type2_dict = get_id2info_dicts(id_mean_df)

In [197]:
len(id2desc_dict), len(id2type1_dict), len(id2type2_dict)

(259, 259, 259)

In [198]:
id2desc_dict

{'610120': '风控分1',
 '61012004': '风控分2',
 '61012005': '场景质量分',
 '61012020': '场景1的催收难度分',
 '61012021': '场景2的催收难度分',
 '2000000134': '年龄分段',
 '2000000136': '性别',
 '2000019444': '健康',
 '2000019464': '工具',
 '2000019469': '金融理财',
 '2000019493': '彩票',
 '2000021475': '京东标签',
 '2000024892': '分辨率离散',
 '2000024893': 'ram大小离散',
 '2000024894': 'api_level',
 '2000024895': 'machine价格离散',
 '2000024897': 'brand',
 '2000024898': 'rom离散',
 '2000024899': 'cpu频率离散',
 '2000024900': 'cpu核数离散',
 '2000024901': 'QQ最近登录地址',
 '2000026099': '原始cpu频率',
 '2000026100': '原始屏幕分辨率',
 '2000026101': '原始ram大小',
 '2000026102': '原始rom大小',
 '2000026103': '原始价格',
 '2000026104': '原始sd卡',
 '2000026105': '原始年龄',
 '2000026113': '资产属性',
 '2000026114': '地址',
 '2000026480': '学历',
 '2000026497': '年龄预测',
 '2000026823': '金融理财',
 '2000027070': '运动健身',
 '2000027071': 'wifi-poi娱乐休闲',
 '2000027072': '银行金融',
 '2000027073': '医疗保险',
 '2000027078': '美食',
 '2000027096': 'wifi',
 '2000027111': 'wifi_poi夜总会',
 '2000027115': '咖啡厅',
 '2000027125': '银行',
 '2000027151': '招聘求职',
 '2000027169': '宠物服务',
 '2000027188': 'wifi_poi小吃快餐',
 '2000027263': '图书音像',
 '2000027365': '湘菜',
 '2000027374': '民族菜',
 '2000027382': '东北菜',
 '2000027441': '信用卡',
 '2000027447': '互联网贷款',
 '2000027845': '移动购物',
 '2000027846': '金融理财',
 '2000027847': '汽车服务',
 '2000027849': '旅游出行',
 '2000027850': '办公商务',
 '2000027851': '移动视频',
 '2000027854': '电话通讯',
 '2000027856': '主题美化',
 '2000027860': '智能设备',
 '2000027861': '手机游戏',
 '2000027862': '新闻资讯',
 '2000027868': '快递',
 '2000027871': '即时通信',
 '2000027872': '论坛贴吧',
 '2000027873': '社区交友',
 '2000027874': '微博社交',
 '2000027875': '婚恋交友',
 '2000027876': '综合电商',
 '2000027879': '跨境电商',
 '2000027884': '综合理财',
 '2000027885': '理财guess1',
 '2000027886': '网上银行',
 '2000027887': '支付结算',
 '2000027888': '网络彩票',
 '2000027889': '记账理财',
 '2000027890': '现金借贷app安装',
 '2000027891': '理财guess2',
 '2000027895': '违章查询安装',
 '2000027896': '汽车交易',
 '2000027899': '营业厅',
 '2000027901': '快递物流',
 '2000027902': '在线团购',
 '2000027910': '家政服务',
 '2000027912': '火车服务',
 '2000027913': '地图导航',
 '2000027915': '在线旅游',
 '2000027918': '旅行工具',
 '2000027920': '民宿短租',
 '2000027927': '在线视频',
 '2000027928': '聚合视频',
 '2000027929': '短视频',
 '2000027942': '照相机',
 '2000027948': '网络电话',
 '2000027951': '词典翻译',
 '2000027953': '学前教育',
 '2000027954': 'K12教育',
 '2000027960': '手机壁纸',
 '2000027970': '安全服务',
 '2000027972': '输入法',
 '2000027974': '应用商店',
 '2000027981': '天气服务',
 '2000027983': '手电筒',
 '2000027993': '棋牌游戏',
 '2000028010': '综合资讯',
 '2000028021': '预约挂号',
 '2000028028': '团购餐饮',
 '2000028040': '快递',
 '2000028044': '职业社交',
 '2000028051': '二手车交易',
 '2000028052': '一手车交易',
 '2000028062': '大王卡用户',
 '2000038128': '逾期',
 '2000039719': '移动购物',
 '2000039720': '金融理财',
 '2000039721': '汽车服务',
 '2000039723': '旅游出行',
 '2000039724': '办公商务',
 '2000039725': '移动视频',
 '2000039726': '移动音乐',
 '2000039731': '数字阅读',
 '2000039740': '餐饮',
 '2000039749': '综合电商',
 '2000039757': '综合理财',
 '2000039758': '理财guess1',
 '2000039759': '网上银行',
 '2000039760': '支付结算',
 '2000039761': '网络彩票',
 '2000039762': '记账理财(使用)',
 '2000039763': '现金借贷app使用',
 '2000039768': '违章查询使用',
 '2000039769': '汽车交易(使用)',
 '2000039771': '汽车社区(使用)',
 '2000039788': '在线旅游',
 '2000039795': '云盘存储',
 '2000039799': '名片管理',
 '2000039815': '照相机',
 '2000039833': '手机壁纸',
 '2000039837': '电子书',
 '2000039854': '天气服务',
 '2000039876': '游戏平台',
 '2000039921': '二手车交易',
 '2000039922': '一手车交易',
 '2000039931': '消费水平',
 '2000039933': '原始屏幕尺寸',
 '2000040011': '籍贯',
 '2000044819': '公积金',
 '2000045217': '教育',
 '2000045218': '公务员',
 '2000051238': '用户行为特征embedding',
 '2000051239': 'NaN',
 '2000051240': '安装软件向量',
 '2000051268': '广告业',
 '2000051324': '旅游',
 '2000051325': '导游',
 '2000052228': '有房',
 '2000052229': '有车',
 '2000053552': '换机标识',
 '2000053668': '你我贷借款APP被安装的月份数',
 '2000053669': '借贷app1被安装的月份数',
 '2000053670': '借贷app2被安装的月份数',
 '2000053672': '借贷app3被安装的月份数',
 '2000053673': '快手APP被安装的月份数',
 '2000053708': '快手使用情况',
 '2000053714': 'qq使用的最多流量(单位M.按月)',
 '2000053715': '支付宝使用的最多流量(单位M.按月)',
 '2000053718': '使用软件向量',
 '2000053719': '使用游戏向量',
 '2000053720': '周新装软件向量',
 '2000053742': '近6个月安装高风险网贷app个数',
 '2000053743': '近3个月安装高风险网贷app个数',
 '2000053744': '近6个月安装网贷app个数',
 '2000053746': '近3个月博彩app安装数',
 '2000053747': '近6个月博彩app安装数',
 '2000053748': '近3个月博彩app安装数',
 '2000053750': '近6个月高风险网贷app使用次数',
 '2000053806': '机龄',
 '2000053837': '收入水平',
 '2000054989': '工薪族',
 '2000054990': '党员',
 '2000055917': '活跃属性',
 '2000055919': 'NaN',
 '2000055935': 'NaN',
 '2000055979': '保险理财',
 '2000055995': '号码一个月内出现的天数',
 '2000055996': '号码两个月内出现的天数',
 '2000055997': '号码三个月内出现的天数',
 '2000055998': '号码六个月内出现的天数',
 '2000056001': '号码一个月内出现的活跃天数',
 '2000056002': '号码一个月内出现的活跃天数',
 '2000056003': '号码两个月内出现的活跃天数',
 '2000056004': '号码三个月内出现的活跃天数',
 '2000056008': '号码一个月内出现的次数',
 '2000056009': '号码两个月内出现的次数',
 '2000056010': '号码三个月内出现的次数',
 '2000056011': '号码六个月内出现的次数',
 '2000056014': '号码一个月内的主动活跃次数',
 '2000056015': '号码两个月内的主动活跃次数',
 '2000056016': '号码三个月内的主动活跃次数',
 '2000056017': '号码六个月内的主动活跃次数',
 '2000056120': 'NaN',
 '2000062874': '风控分',
 '2000064725': '通用模型风控分',
 '2000064741': 'phone-imei光系',
 '2000064998': '最近一个月有逾期',
 '2000064999': '最近三个月有逾期',
 '2000065000': '最近半年有逾期',
 '2000065339': '银行贷款累计有逾期',
 '2000065001': '网贷累计有逾期',
 '2000065004': '最近半年有严重逾期',
 '2000065005': '累计有严重逾期',
 '2000065022': '最近一个月有放款',
 '2000065023': '最近三个月有放款',
 '2000065264': 'URL行为',
 '2000065265': '欺诈挂马',
 '2000065267': '色情',
 '2000065268': '反动言论',
 '2000065391': '线上现金分期信用分',
 '2000065392': '信用卡代偿场景分',
 '2000065393': '线上现金分期分',
 '2000065394': '线上消费分期场景分',
 '2000065395': '线上现金&消费分期信用分',
 '2000065396': '通用模型分1',
 '2000065397': '现金借贷大额长期场景分',
 '2000065398': '消费分期信用分v2',
 '2000065399': '现金借贷小额短期场景分',
 '2000065400': '通用场景信用分',
 '2000065401': '通用场景信用分v2',
 '2000065556': '一年内拨打保险公司的天数',
 '2000065559': '收支流水分模型',
 '2000065564': '个体户',
 '2000065567': '个体户老板or管理人员',
 '2000065621': '拍拍贷定制模型大额长期v2模型分',
 '2000065813': '信用卡额度分模型',
 '2000065814': '工资水平模型',
 '2000065815': '消费分模型',
 '2000065816': '账单支付模型',
 '2000065840': '通用模型v2',
 '2000065841': '现金借贷大额长期v2',
 '2000065842': '消费分期v2',
 '2000065843': '现金借贷小额短期v2',
 '2000065844': '平台样本v2',
 '2000065845': '未知场景样本v2',
 '2000065850': '1个月申请机构数',
 '2000065851': '3个月申请机构数',
 '2000065852': '6个月申请机构数',
 '2000065864': '公积金分数模型',
 '2000065865': '资产通用分',
 '2000065871': '信用卡额度扩散',
 '2000065941': '通用模型v3',
 '2000065942': '现金借贷大额长期v3模型分',
 '2000666662': '是否有逾期',
 '8666610001': '扩散通用模型分',
 '8666710001': '扩散大额长期场景模型分',
 '8666810001': '扩散消费分期模型分',
 '8667110001': '扩散未知场景模型分',
 '8668610009': 'wifi扩散通用场景分',
 '8668610011': 'wifi扩散消费分期场景模型分',
 '8668610014': 'wifi扩散未知场景模型分'}

In [199]:
id2type1_dict

{'610120': 'NaN',
 '61012004': 'NaN',
 '61012005': 'NaN',
 '61012020': 'NaN',
 '61012021': 'NaN',
 '2000000134': 'NaN',
 '2000000136': 'NaN',
 '2000019444': 'NaN',
 '2000019464': 'NaN',
 '2000019469': 'NaN',
 '2000019493': 'NaN',
 '2000021475': 'NaN',
 '2000024892': 'NaN',
 '2000024893': 'NaN',
 '2000024894': 'NaN',
 '2000024895': 'NaN',
 '2000024897': 'NaN',
 '2000024898': 'NaN',
 '2000024899': 'NaN',
 '2000024900': 'NaN',
 '2000024901': 'NaN',
 '2000026099': 'NaN',
 '2000026100': 'NaN',
 '2000026101': 'NaN',
 '2000026102': 'NaN',
 '2000026103': 'NaN',
 '2000026104': 'NaN',
 '2000026105': 'NaN',
 '2000026113': 'NaN',
 '2000026114': 'NaN',
 '2000026480': 'NaN',
 '2000026497': 'NaN',
 '2000026823': 'NaN',
 '2000027070': 'NaN',
 '2000027071': 'NaN',
 '2000027072': 'NaN',
 '2000027073': 'NaN',
 '2000027078': 'NaN',
 '2000027096': 'NaN',
 '2000027111': 'NaN',
 '2000027115': 'NaN',
 '2000027125': 'NaN',
 '2000027151': 'NaN',
 '2000027169': 'NaN',
 '2000027188': 'NaN',
 '2000027263': 'NaN',
 '2000027365': 'NaN',
 '2000027374': 'NaN',
 '2000027382': 'NaN',
 '2000027441': 'NaN',
 '2000027447': 'NaN',
 '2000027845': 'app 安装',
 '2000027846': 'app 安装',
 '2000027847': 'app 安装',
 '2000027849': 'app 安装',
 '2000027850': 'app 安装',
 '2000027851': 'app 安装',
 '2000027854': 'app 安装',
 '2000027856': 'app 安装',
 '2000027860': 'app 安装',
 '2000027861': 'app 安装',
 '2000027862': 'app 安装',
 '2000027868': 'app 安装',
 '2000027871': 'app 安装',
 '2000027872': 'app 安装',
 '2000027873': 'app 安装',
 '2000027874': 'app 安装',
 '2000027875': 'app 安装',
 '2000027876': 'app 安装',
 '2000027879': 'app 安装',
 '2000027884': 'app 安装',
 '2000027885': 'app 安装',
 '2000027886': 'app 安装',
 '2000027887': 'app 安装',
 '2000027888': 'app 安装',
 '2000027889': 'app 安装',
 '2000027890': 'app 安装',
 '2000027891': 'app 安装',
 '2000027895': 'app 安装',
 '2000027896': 'app 安装',
 '2000027899': 'app 安装',
 '2000027901': 'app 安装',
 '2000027902': 'app 安装',
 '2000027910': 'app 安装',
 '2000027912': 'app 安装',
 '2000027913': 'app 安装',
 '2000027915': 'app 安装',
 '2000027918': 'app 安装',
 '2000027920': 'app 安装',
 '2000027927': 'app 安装',
 '2000027928': 'app 安装',
 '2000027929': 'app 安装',
 '2000027942': 'app 安装',
 '2000027948': 'app 安装',
 '2000027951': 'app 安装',
 '2000027953': 'app 安装',
 '2000027954': 'app 安装',
 '2000027960': 'app 安装',
 '2000027970': 'app 安装',
 '2000027972': 'app 安装',
 '2000027974': 'app 安装',
 '2000027981': 'app 安装',
 '2000027983': 'app 安装',
 '2000027993': 'app 安装',
 '2000028010': 'app 安装',
 '2000028021': 'app 安装',
 '2000028028': 'app 安装',
 '2000028040': 'app 安装',
 '2000028044': 'app 安装',
 '2000028051': 'app 安装',
 '2000028052': 'app 安装',
 '2000028062': 'NaN',
 '2000038128': 'NaN',
 '2000039719': 'app使用',
 '2000039720': 'app使用',
 '2000039721': 'app使用',
 '2000039723': 'app使用',
 '2000039724': 'app使用',
 '2000039725': 'app使用',
 '2000039726': 'app使用',
 '2000039731': 'app使用',
 '2000039740': 'app使用',
 '2000039749': 'app使用',
 '2000039757': 'app使用',
 '2000039758': 'app使用',
 '2000039759': 'app使用',
 '2000039760': 'app使用',
 '2000039761': 'app使用',
 '2000039762': 'app使用',
 '2000039763': 'app使用',
 '2000039768': 'app使用',
 '2000039769': 'app使用',
 '2000039771': 'app使用',
 '2000039788': 'app使用',
 '2000039795': 'app使用',
 '2000039799': 'app使用',
 '2000039815': 'app使用',
 '2000039833': 'app使用',
 '2000039837': 'app使用',
 '2000039854': 'app使用',
 '2000039876': 'app使用',
 '2000039921': 'app使用',
 '2000039922': 'app使用',
 '2000039931': 'NaN',
 '2000039933': 'NaN',
 '2000040011': 'NaN',
 '2000044819': 'NaN',
 '2000045217': 'NaN',
 '2000045218': 'NaN',
 '2000051238': 'NaN',
 '2000051239': 'NaN',
 '2000051240': 'NaN',
 '2000051268': 'NaN',
 '2000051324': 'NaN',
 '2000051325': 'NaN',
 '2000052228': 'NaN',
 '2000052229': 'NaN',
 '2000053552': 'NaN',
 '2000053668': 'NaN',
 '2000053669': 'NaN',
 '2000053670': 'NaN',
 '2000053672': 'NaN',
 '2000053673': 'NaN',
 '2000053708': 'NaN',
 '2000053714': 'NaN',
 '2000053715': 'NaN',
 '2000053718': 'NaN',
 '2000053719': 'NaN',
 '2000053720': 'NaN',
 '2000053742': 'NaN',
 '2000053743': 'NaN',
 '2000053744': 'NaN',
 '2000053746': 'NaN',
 '2000053747': 'NaN',
 '2000053748': 'NaN',
 '2000053750': 'NaN',
 '2000053806': 'NaN',
 '2000053837': 'NaN',
 '2000054989': 'NaN',
 '2000054990': 'NaN',
 '2000055917': 'NaN',
 '2000055919': 'NaN',
 '2000055935': 'NaN',
 '2000055979': 'NaN',
 '2000055995': 'NaN',
 '2000055996': 'NaN',
 '2000055997': 'NaN',
 '2000055998': 'NaN',
 '2000056001': 'NaN',
 '2000056002': 'NaN',
 '2000056003': 'NaN',
 '2000056004': 'NaN',
 '2000056008': 'NaN',
 '2000056009': 'NaN',
 '2000056010': 'NaN',
 '2000056011': 'NaN',
 '2000056014': 'NaN',
 '2000056015': 'NaN',
 '2000056016': 'NaN',
 '2000056017': 'NaN',
 '2000056120': 'NaN',
 '2000062874': 'NaN',
 '2000064725': 'NaN',
 '2000064741': 'NaN',
 '2000064998': 'NaN',
 '2000064999': 'NaN',
 '2000065000': 'NaN',
 '2000065339': 'NaN',
 '2000065001': 'NaN',
 '2000065004': 'NaN',
 '2000065005': 'NaN',
 '2000065022': 'NaN',
 '2000065023': 'NaN',
 '2000065264': 'NaN',
 '2000065265': 'NaN',
 '2000065267': 'NaN',
 '2000065268': 'NaN',
 '2000065391': '分数',
 '2000065392': '分数',
 '2000065393': '分数',
 '2000065394': '分数',
 '2000065395': '分数',
 '2000065396': 'NaN',
 '2000065397': 'NaN',
 '2000065398': 'NaN',
 '2000065399': 'NaN',
 '2000065400': 'NaN',
 '2000065401': 'NaN',
 '2000065556': 'NaN',
 '2000065559': 'NaN',
 '2000065564': 'NaN',
 '2000065567': 'NaN',
 '2000065621': '模型分',
 '2000065813': 'NaN',
 '2000065814': 'NaN',
 '2000065815': 'NaN',
 '2000065816': 'NaN',
 '2000065840': 'NaN',
 '2000065841': 'NaN',
 '2000065842': 'NaN',
 '2000065843': 'NaN',
 '2000065844': 'NaN',
 '2000065845': 'NaN',
 '2000065850': 'NaN',
 '2000065851': 'NaN',
 '2000065852': 'NaN',
 '2000065864': 'NaN',
 '2000065865': 'NaN',
 '2000065871': 'NaN',
 '2000065941': 'NaN',
 '2000065942': 'NaN',
 '2000666662': 'NaN',
 '8666610001': 'NaN',
 '8666710001': 'NaN',
 '8666810001': 'NaN',
 '8667110001': 'NaN',
 '8668610009': 'NaN',
 '8668610011': 'NaN',
 '8668610014': 'NaN'}

In [200]:
id2type2_dict

{'610120': 'NaN',
 '61012004': 'NaN',
 '61012005': 'NaN',
 '61012020': 'NaN',
 '61012021': 'NaN',
 '2000000134': '人口属性',
 '2000000136': '人口属性',
 '2000019444': '健康',
 '2000019464': 'NaN',
 '2000019469': '理财',
 '2000019493': '理财',
 '2000021475': '消费',
 '2000024892': '设备属性',
 '2000024893': '设备属性',
 '2000024894': '设备属性',
 '2000024895': '设备属性',
 '2000024897': '设备属性',
 '2000024898': '设备属性',
 '2000024899': '设备属性',
 '2000024900': '设备属性',
 '2000024901': 'NaN',
 '2000026099': '设备属性',
 '2000026100': '设备属性',
 '2000026101': '设备属性',
 '2000026102': '设备属性',
 '2000026103': '设备属性',
 '2000026104': '设备属性',
 '2000026105': '人口属性',
 '2000026113': '资产',
 '2000026114': '人口属性',
 '2000026480': '人口属性',
 '2000026497': '人口属性',
 '2000026823': '理财',
 '2000027070': '自我成长，健康',
 '2000027071': 'wifi',
 '2000027072': '理财',
 '2000027073': '理财',
 '2000027078': '餐饮',
 '2000027096': 'wifi',
 '2000027111': 'wifi',
 '2000027115': '餐饮',
 '2000027125': '理财',
 '2000027151': 'NaN',
 '2000027169': '消费',
 '2000027188': '餐饮',
 '2000027263': '自我成长',
 '2000027365': '餐饮',
 '2000027374': '餐饮',
 '2000027382': '餐饮',
 '2000027441': '贷款',
 '2000027447': '贷款',
 '2000027845': '消费',
 '2000027846': '理财',
 '2000027847': '汽车服务',
 '2000027849': '旅游出行',
 '2000027850': '商务',
 '2000027851': '娱乐',
 '2000027854': '通讯',
 '2000027856': 'NaN',
 '2000027860': 'NaN',
 '2000027861': '娱乐',
 '2000027862': '咨询',
 '2000027868': '消费',
 '2000027871': '社交，通讯',
 '2000027872': '实事',
 '2000027873': '社交',
 '2000027874': '社交',
 '2000027875': '社交',
 '2000027876': '消费',
 '2000027879': '消费',
 '2000027884': '理财',
 '2000027885': '理财',
 '2000027886': '理财',
 '2000027887': '理财',
 '2000027888': '理财',
 '2000027889': '理财',
 '2000027890': '理财',
 '2000027891': '理财',
 '2000027895': 'NaN',
 '2000027896': '汽车服务',
 '2000027899': 'NaN',
 '2000027901': '消费',
 '2000027902': '消费',
 '2000027910': '家庭',
 '2000027912': '旅游出行',
 '2000027913': '旅游出行',
 '2000027915': '旅游出行',
 '2000027918': '旅游出行',
 '2000027920': '旅游出行',
 '2000027927': '娱乐',
 '2000027928': '娱乐',
 '2000027929': '娱乐',
 '2000027942': 'NaN',
 '2000027948': '通讯',
 '2000027951': '自我成长',
 '2000027953': '育儿，家庭',
 '2000027954': 'NaN',
 '2000027960': 'NaN',
 '2000027970': 'NaN',
 '2000027972': 'NaN',
 '2000027974': 'NaN',
 '2000027981': '旅游出行',
 '2000027983': 'NaN',
 '2000027993': '娱乐',
 '2000028010': '实事',
 '2000028021': '医疗',
 '2000028028': '餐饮',
 '2000028040': '消费',
 '2000028044': '社交',
 '2000028051': '汽车服务',
 '2000028052': '汽车服务',
 '2000028062': 'NaN',
 '2000038128': 'NaN',
 '2000039719': '消费',
 '2000039720': '理财',
 '2000039721': '汽车服务',
 '2000039723': '旅游出行',
 '2000039724': '商务',
 '2000039725': '娱乐',
 '2000039726': '娱乐',
 '2000039731': '自我成长',
 '2000039740': '餐饮',
 '2000039749': '消费',
 '2000039757': '理财',
 '2000039758': '理财',
 '2000039759': '理财',
 '2000039760': '理财',
 '2000039761': '理财',
 '2000039762': '理财',
 '2000039763': '理财',
 '2000039768': 'NaN',
 '2000039769': '汽车服务',
 '2000039771': '汽车服务',
 '2000039788': '旅游出行',
 '2000039795': 'NaN',
 '2000039799': '商务',
 '2000039815': 'NaN',
 '2000039833': 'NaN',
 '2000039837': '自我成长',
 '2000039854': '旅游出行',
 '2000039876': '娱乐',
 '2000039921': '汽车服务',
 '2000039922': '汽车服务',
 '2000039931': '资产',
 '2000039933': '设备属性',
 '2000040011': '人口属性',
 '2000044819': '资产',
 '2000045217': '人口属性',
 '2000045218': '人口属性',
 '2000051238': 'NaN',
 '2000051239': 'NaN',
 '2000051240': 'NaN',
 '2000051268': 'NaN',
 '2000051324': '旅游出行',
 '2000051325': '旅游出行',
 '2000052228': '资产',
 '2000052229': '资产',
 '2000053552': '设备属性',
 '2000053668': '贷款',
 '2000053669': '贷款',
 '2000053670': '贷款',
 '2000053672': '贷款',
 '2000053673': '娱乐',
 '2000053708': '娱乐',
 '2000053714': 'NaN',
 '2000053715': 'NaN',
 '2000053718': 'NaN',
 '2000053719': '娱乐',
 '2000053720': 'NaN',
 '2000053742': '高危',
 '2000053743': '高危',
 '2000053744': '高危',
 '2000053746': '高危',
 '2000053747': '高危',
 '2000053748': '高危',
 '2000053750': '高危',
 '2000053806': '设备属性',
 '2000053837': '资产',
 '2000054989': '社会属性',
 '2000054990': '社会属性',
 '2000055917': 'NaN',
 '2000055919': 'NaN',
 '2000055935': 'NaN',
 '2000055979': '理财',
 '2000055995': 'NaN',
 '2000055996': 'NaN',
 '2000055997': 'NaN',
 '2000055998': 'NaN',
 '2000056001': 'NaN',
 '2000056002': 'NaN',
 '2000056003': 'NaN',
 '2000056004': 'NaN',
 '2000056008': 'NaN',
 '2000056009': 'NaN',
 '2000056010': 'NaN',
 '2000056011': 'NaN',
 '2000056014': 'NaN',
 '2000056015': 'NaN',
 '2000056016': 'NaN',
 '2000056017': 'NaN',
 '2000056120': 'NaN',
 '2000062874': 'NaN',
 '2000064725': 'NaN',
 '2000064741': 'NaN',
 '2000064998': '逾期类',
 '2000064999': '逾期类',
 '2000065000': '逾期类',
 '2000065339': '逾期类',
 '2000065001': '逾期类',
 '2000065004': '逾期类',
 '2000065005': '逾期类',
 '2000065022': '贷款行为',
 '2000065023': '贷款行为',
 '2000065264': '高危行为',
 '2000065265': '高危行为',
 '2000065267': '高危行为',
 '2000065268': '高危行为',
 '2000065391': 'NaN',
 '2000065392': 'NaN',
 '2000065393': 'NaN',
 '2000065394': 'NaN',
 '2000065395': 'NaN',
 '2000065396': 'NaN',
 '2000065397': 'NaN',
 '2000065398': 'NaN',
 '2000065399': 'NaN',
 '2000065400': 'NaN',
 '2000065401': 'NaN',
 '2000065556': 'NaN',
 '2000065559': '资产分属性',
 '2000065564': 'NaN',
 '2000065567': 'NaN',
 '2000065621': 'v2反欺诈分',
 '2000065813': '资产分属性',
 '2000065814': '资产分属性',
 '2000065815': 'NaN',
 '2000065816': 'NaN',
 '2000065840': 'v2反欺诈分',
 '2000065841': 'v2反欺诈分',
 '2000065842': 'v2反欺诈分',
 '2000065843': 'v2反欺诈分',
 '2000065844': 'v2反欺诈分',
 '2000065845': 'v2反欺诈分',
 '2000065850': '申请多头',
 '2000065851': '申请多头',
 '2000065852': '申请多头',
 '2000065864': '资产分属性',
 '2000065865': '资产分属性',
 '2000065871': '资产分属性',
 '2000065941': 'v3反欺诈分',
 '2000065942': 'v3反欺诈分',
 '2000666662': 'v3版反欺诈分底层特征',
 '8666610001': 'v3版反欺诈分底层特征',
 '8666710001': 'v3版反欺诈分底层特征',
 '8666810001': 'v3版反欺诈分底层特征',
 '8667110001': 'v3版反欺诈分底层特征',
 '8668610009': 'v3版反欺诈分底层特征',
 '8668610011': 'v3版反欺诈分底层特征',
 '8668610014': 'v3版反欺诈分底层特征'}

In [172]:
id2desc_dict['2000000134']

'年龄分段'

In [223]:
def get_id2desc_of_type(id2type_dict, id2desc_dict, type_list):
    selected_id2desc_dict = dict()
    selected_id2type_dict = dict()
    selected_ids_list = list()
    for key, val in id2type_dict.items():
        if val in type_list:
#             print(key, type(key))
            print(key, id2desc_dict[key])
            selected_id2desc_dict[key] = id2desc_dict[key]
            selected_id2type_dict[key] = val
            selected_ids_list.append(key)
    return selected_id2desc_dict, selected_id2type_dict, selected_ids_list

In [212]:
sel_id2desc_dict, sel_id2type_dict, sel_ids_list = get_id2desc_of_type(id2type_dict, id2desc_dict, ["人口属性", "社会属性"])

2000000134 年龄分段
2000000136 性别
2000026105 原始年龄
2000026114 地址
2000026480 学历
2000026497 年龄预测
2000040011 籍贯
2000045217 教育
2000045218 公务员
2000054989 工薪族
2000054990 党员

In [182]:
sel_id2desc_dict, sel_ids_list

({'2000000134': '年龄分段',
  '2000000136': '性别',
  '2000026105': '原始年龄',
  '2000026114': '地址',
  '2000026480': '学历',
  '2000026497': '年龄预测',
  '2000040011': '籍贯',
  '2000045217': '教育',
  '2000045218': '公务员',
  '2000054989': '工薪族',
  '2000054990': '党员'},
 ['2000000134',
  '2000000136',
  '2000026105',
  '2000026114',
  '2000026480',
  '2000026497',
  '2000040011',
  '2000045217',
  '2000045218',
  '2000054989',
  '2000054990'])

In [38]:
equip_id2name = dict()
for key, val in id2type_dict.items():
    if val == "设备属性":
        print(key, id2tag_dict[key], type(key), type(id2tag_dict[key]))
        equip_id2name[key] = id2tag_dict[key]

2000024892 分辨率离散 <class 'str'> <class 'str'>
2000024893 ram大小离散 <class 'str'> <class 'str'>
2000024894 api_level <class 'str'> <class 'str'>
2000024895 machine价格离散 <class 'str'> <class 'str'>
2000024897 brand <class 'str'> <class 'str'>
2000024898 rom离散 <class 'str'> <class 'str'>
2000024899 cpu频率离散 <class 'str'> <class 'str'>
2000024900 cpu核数离散 <class 'str'> <class 'str'>
2000026099 原始cpu频率 <class 'str'> <class 'str'>
2000026100 原始屏幕分辨率 <class 'str'> <class 'str'>
2000026101 原始ram大小 <class 'str'> <class 'str'>
2000026102 原始rom大小 <class 'str'> <class 'str'>
2000026103 原始价格 <class 'str'> <class 'str'>
2000026104 原始sd卡 <class 'str'> <class 'str'>
2000039933 原始屏幕尺寸 <class 'str'> <class 'str'>
2000053552 换机标识 <class 'str'> <class 'str'>
2000053806 机龄 <class 'str'> <class 'str'>

In [39]:
equip_id2name

{'2000024892': '分辨率离散',
 '2000024893': 'ram大小离散',
 '2000024894': 'api_level',
 '2000024895': 'machine价格离散',
 '2000024897': 'brand',
 '2000024898': 'rom离散',
 '2000024899': 'cpu频率离散',
 '2000024900': 'cpu核数离散',
 '2000026099': '原始cpu频率',
 '2000026100': '原始屏幕分辨率',
 '2000026101': '原始ram大小',
 '2000026102': '原始rom大小',
 '2000026103': '原始价格',
 '2000026104': '原始sd卡',
 '2000039933': '原始屏幕尺寸',
 '2000053552': '换机标识',
 '2000053806': '机龄'}

In [41]:
equipment_df.rename(columns=equip_id2name, inplace=True)

In [56]:
equipment_df.head(20)

,分辨率离散,ram大小离散,api_level,machine价格离散,rom离散,cpu频率离散,cpu核数离散,原始cpu频率,原始屏幕分辨率,原始ram大小,原始rom大小,原始价格,原始sd卡,原始屏幕尺寸,机龄,换机标识
0,10.0,11.0,28.0,6.0,20.0,22.0,8.0,1844000.0,1950480.0,5726.0,115401.0,2380.0,113310.0,5.70,25.0,NaN
1,8.0,8.0,27.0,NaN,18.0,22.0,8.0,1804800.0,1036800.0,2820.0,27896.0,NaN,25318.0,NaN,0.0,NaN
2,11.0,11.0,27.0,3.0,21.0,22.0,8.0,1843200.0,2293920.0,3744.0,113858.0,878.0,109953.0,5.88,4.0,NaN
3,11.0,10.0,26.0,5.0,19.0,21.0,8.0,1709000.0,2322000.0,3788.0,56064.0,1999.0,52658.0,5.84,11.0,NaN
4,11.0,11.0,28.0,NaN,20.0,23.0,8.0,2000000.0,2304720.0,5618.0,116162.0,NaN,112691.0,NaN,0.0,NaN
5,8.0,8.0,23.0,4.0,18.0,12.0,8.0,1401000.0,921600.0,2835.0,28143.0,1299.0,25633.0,5.20,24.0,NaN
6,11.0,11.0,28.0,7.0,20.0,22.0,8.0,1843200.0,2377080.0,5703.0,114553.0,2698.0,110384.0,6.01,15.0,NaN
7,11.0,12.0,28.0,0.0,21.0,22.0,8.0,1766400.0,2253960.0,7638.0,233695.0,0.0,230925.0,0.00,16.0,NaN
8,8.0,10.0,28.0,4.0,20.0,21.0,8.0,1709000.0,978480.0,3784.0,116388.0,1309.0,113078.0,5.93,20.0,NaN
9,11.0,10.0,28.0,9.0,19.0,22.0,8.0,1844000.0,2073600.0,3689.0,56182.0,3899.0,53970.0,5.90,15.0,NaN
10,5.0,6.0,22.0,3.0,15.0,11.0,4.0,1209600.0,518400.0,1905.0,13974.0,998.0,10998.0,5.00,35.0,NaN
11,11.0,9.0,27.0,0.0,19.0,22.0,8.0,1804800.0,2229120.0,3473.0,55347.0,0.0,51443.0,0.00,10.0,NaN
12,11.0,10.0,26.0,4.0,19.0,21.0,8.0,1709000.0,2201040.0,3789.0,56806.0,1299.0,53842.0,5.93,17.0,NaN
13,8.0,9.0,27.0,4.0,19.0,22.0,8.0,1804800.0,1094400.0,3569.0,56092.0,1500.0,52231.0,6.20,4.0,NaN
14,11.0,10.0,27.0,7.0,19.0,22.0,8.0,1843200.0,2073600.0,3740.0,56479.0,2999.0,53113.0,6.01,23.0,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,11.0,10.0,28.0,7.0,20.0,22.0,8.0,1785600.0,4210560.0,NaN,111751.0,NaN,108387.0,NaN,42.0,NaN
17,11.0,12.0,27.0,5.0,20.0,21.0,8.0,1708800.0,2527200.0,7623.0,115759.0,1799.0,111105.0,6.40,12.0,NaN
18,11.0,12.0,28.0,8.0,21.0,22.0,8.0,1766400.0,2203200.0,7638.0,236946.0,3299.0,233970.0,5.99,13.0,NaN
19,8.0,8.0,22.0,4.0,15.0,17.0,8.0,1508000.0,921600.0,2761.0,14035.0,1399.0,10459.0,5.50,34.0,NaN

In [60]:
demo_df = pd.read_csv('../../../data/cell_manager/demographics.csv')

In [61]:
demo_df.shape

(177986, 8)

In [62]:
demo_df.head(20)

,2000000134,2000026105,2000026480,2000026497,2000045217,2000054990,2000054989,2000045218
0,3.0,19.0,5.0,2.0,NaN,1.0,NaN,NaN
1,4.0,25.0,4.0,3.0,NaN,NaN,1.0,NaN
2,3.0,23.0,4.0,2.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3.0,21.0,5.0,2.0,NaN,NaN,NaN,NaN
6,3.0,20.0,4.0,2.0,NaN,NaN,NaN,NaN
7,4.0,25.0,4.0,3.0,NaN,NaN,NaN,NaN
8,6.0,41.0,4.0,4.0,NaN,NaN,NaN,NaN
9,2.0,17.0,6.0,1.0,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,0.8,NaN,NaN,0.8
11,7.0,46.0,3.0,4.0,NaN,NaN,NaN,NaN
12,4.0,41.0,6.0,3.0,NaN,NaN,NaN,NaN
13,5.0,35.0,1.0,4.0,NaN,NaN,NaN,NaN
14,4.0,26.0,0.0,3.0,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,3.0,20.0,5.0,2.0,NaN,NaN,NaN,NaN
17,4.0,25.0,5.0,3.0,NaN,NaN,NaN,NaN
18,3.0,22.0,5.0,2.0,NaN,NaN,NaN,NaN
19,4.0,28.0,4.0,3.0,0.8,NaN,NaN,0.8

In [63]:
demo_df.rename(columns=demo_id2name, inplace=True)

In [74]:
demo_df.head(10)

   年龄分段  原始年龄   学历  年龄预测  教育   党员  工薪族  公务员
0   3.0  19.0  5.0   2.0 NaN  1.0  NaN  NaN
1   4.0  25.0  4.0   3.0 NaN  NaN  1.0  NaN
2   3.0  23.0  4.0   2.0 NaN  NaN  NaN  NaN
3   NaN   NaN  NaN   NaN NaN  NaN  NaN  NaN
4   NaN   NaN  NaN   NaN NaN  NaN  NaN  NaN
5   3.0  21.0  5.0   2.0 NaN  NaN  NaN  NaN
6   3.0  20.0  4.0   2.0 NaN  NaN  NaN  NaN
7   4.0  25.0  4.0   3.0 NaN  NaN  NaN  NaN
8   6.0  41.0  4.0   4.0 NaN  NaN  NaN  NaN
9   2.0  17.0  6.0   1.0 NaN  NaN  NaN  NaN

In [75]:
demo_df.describe()

,年龄分段,原始年龄,学历,年龄预测,教育,党员,工薪族,公务员
count,141399.000000,134935.00000,141095.000000,134362.000000,5.119000e+03,5669.0,5681.0,1.304000e+03
mean,3.651787,24.14046,3.808618,2.410756,8.000000e-01,1.0,1.0,8.000000e-01
std,1.433022,7.87702,1.546119,1.073370,7.483634e-14,0.0,0.0,1.921423e-14
min,1.000000,0.00000,0.000000,0.000000,8.000000e-01,1.0,1.0,8.000000e-01
25%,3.000000,19.00000,3.000000,2.000000,8.000000e-01,1.0,1.0,8.000000e-01
50%,3.000000,23.00000,4.000000,2.000000,8.000000e-01,1.0,1.0,8.000000e-01
75%,4.000000,29.00000,5.000000,3.000000,8.000000e-01,1.0,1.0,8.000000e-01
max,9.000000,100.00000,6.000000,5.000000,8.000000e-01,1.0,1.0,8.000000e-01

In [66]:
demo_df['年龄分段'].unique()

array([ 3.,  4., nan,  6.,  2.,  7.,  5.,  1.,  9.,  8.])

In [67]:
demo_df['原始年龄'].unique()

array([ 19.,  25.,  23.,  nan,  21.,  20.,  41.,  17.,  46.,  35.,  26.,
        22.,  28.,  27.,  13.,  53.,  14.,  18.,  38.,  15.,  29.,  30.,
        16.,  12.,  24.,  31.,  32.,  34.,  33.,  36.,  44.,  49.,  45.,
        40.,  10.,  42.,  37.,  39.,   0.,  51.,  47.,   1.,  43.,  55.,
        61.,  56.,  60.,  11.,  54.,  48.,  52.,  50.,   9.,  59.,   3.,
         6.,   4.,   2.,   5.,   8.,  67.,  66.,  73.,  57., 100.,  64.,
         7.,  78.,  79.,  74.,  62.,  58.,  68.,  71.,  63.,  75.,  70.,
        72.,  69.,  65.,  77.])

In [68]:
demo_df['学历'].unique()

array([ 5.,  4., nan,  6.,  3.,  1.,  0.,  2.])

In [69]:
demo_df['年龄预测'].unique()

array([ 2.,  3., nan,  4.,  1.,  5.,  0.])

In [70]:
demo_df['教育'].unique()

array([nan, 0.8])

In [71]:
demo_df['党员'].unique()

array([ 1., nan])

In [72]:
demo_df['工薪族'].unique()

array([nan,  1.])

In [73]:
demo_df['公务员'].unique()

array([nan, 0.8])

In [82]:
risk_df = pd.read_csv('../../../data/cell_manager/risk.txt', header=None)
risk_ids = [str(val) for val in risk_df.iloc[0].values]

In [84]:
# risk_ids

In [94]:
selected_risk_ids = []
for key, val in id2tag_dict.items():
    val_id = key[:10]
#     print(val)
    if val_id in risk_ids:
        print(key, val)
        selected_risk_ids.append(key)

2000027070 运动健身
2000027071 wifi-poi娱乐休闲
2000027072 银行金融
2000027073 医疗保险
2000027078 美食
2000027096 wifi
2000027111 wifi_poi夜总会
2000027115 咖啡厅
2000027125 银行
2000027151 招聘求职
2000027169 宠物服务
2000027188 wifi_poi小吃快餐
2000027263 图书音像
2000027365 湘菜
2000027374 民族菜
2000027382 东北菜
2000053668 你我贷借款APP被安装的月份数
2000053669 借贷app1被安装的月份数
2000053670 借贷app2被安装的月份数
2000053672 借贷app3被安装的月份数
2000053673 快手APP被安装的月份数
2000053708 快手使用情况
2000053714 qq使用的最多流量(单位M.按月)
2000053715 支付宝使用的最多流量(单位M.按月)
2000053742 近6个月安装高风险网贷app个数
2000053743 近3个月安装高风险网贷app个数
2000053744 近6个月安装网贷app个数
2000053746 近3个月博彩app安装数
2000053747 近6个月博彩app安装数
2000053748 近3个月博彩app安装数
2000053750 近6个月高风险网贷app使用次数
2000064998 最近一个月有逾期
2000064999 最近三个月有逾期
2000065000 最近半年有逾期
2000065001 累计有逾期
2000065004 最近半年有严重逾期
2000065005 累计有严重逾期
2000065022 最近一个月有放款
2000065023 最近三个月有放款
2000065265 欺诈,挂马
2000065267 色情

In [97]:
type(selected_risk_ids)

list

In [119]:
# app_install_df = pd.read_csv('../../../data/cell_manager/app.txt', header=None)
# app_install_ids = [str(val) for val in app_install_df.iloc[0].values]

In [117]:
# for key, val in id2tag_dict.items():
#     val_id = key[:10]
# #     print(val)
#     if val_id in app_install_ids:
#         print(key, val)

In [115]:
# A_train_df = pd.read_csv('../../../data/cell_manager/A_train.csv')

In [116]:
# A_train_df.head(5)

In [111]:
risk_df = A_train_df[selected_risk_ids[:20]]

In [112]:
risk_df.describe()

,2000027070,2000027071,2000027072,2000027073,2000027078,2000027096,2000027111,2000027115,2000027125,2000027151,2000027169,2000027188,2000027263,2000027365,2000027374,2000027382,2000053668,2000053669,2000053670,2000053672
count,4624.000000,35318.000000,4457.000000,11868.000000,59451.000000,1116.0,434.0,1981.0,3223.0,429.0,435.0,26049.0,634.0,3731.0,235.0,938.0,2662.000000,7407.000000,16394.000000,4550.000000
mean,14.006055,24.537658,13.661656,23.452899,17.143109,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.794140,3.414338,2.884104,2.323736
std,126.143136,292.003161,89.503575,252.466786,187.651655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.146862,3.611863,3.144207,2.778325
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000
50%,1.000000,1.000000,1.000000,1.000000,2.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.000000,1.000000,1.000000
75%,4.000000,7.000000,3.000000,5.000000,8.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.000000,5.000000,4.000000,2.000000
max,6943.000000,26208.000000,2127.000000,17869.000000,32197.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,12.000000,12.000000,12.000000,12.000000

In [120]:
risk_df = A_train_df[selected_risk_ids[20:41]]

In [121]:
risk_df.describe()

,2000053673,2000053708,2000053714,2000053715,2000053742,2000053743,2000053744,2000053746,2000053747,2000053748,...,2000064998,2000064999,2000065000,2000065001,2000065004,2000065005,2000065022,2000065023,2000065265,2000065267
count,93898.000000,4.989600e+04,8.278900e+04,82271.000000,6757.000000,5833.000000,33866.000000,2113.000000,2723.000000,2113.000000,...,1290.000000,2352.000000,2672.000000,3265.000000,721.000000,926.000000,3167.000000,5213.000000,12432.0,14250.0
mean,4.993855,6.762280e+04,3.023115e+04,2442.123519,1.160130,1.148809,1.420717,1.088973,1.108336,1.088973,...,1.550388,1.665816,1.868263,2.925881,2.273232,4.212743,1.229555,1.391329,1.0,1.0
std,4.294999,2.915929e+05,1.799337e+05,9792.359459,0.521409,0.504240,0.932502,0.371367,0.417755,0.371367,...,2.179890,3.201800,4.816188,15.757119,5.544163,16.977158,0.577564,0.865658,0.0,0.0
min,1.000000,0.000000e+00,0.000000e+00,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0
25%,1.000000,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0
50%,3.000000,1.863000e+03,1.012000e+03,364.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0
75%,9.000000,3.082525e+04,9.404000e+03,1675.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.0,1.0
max,12.000000,9.070421e+06,9.375700e+06,950008.000000,9.000000,9.000000,24.000000,8.000000,8.000000,8.000000,...,22.000000,41.000000,59.000000,243.000000,37.000000,148.000000,6.000000,14.000000,1.0,1.0

In [124]:
capital = A_train_df[["2000026113", "2000053837", "2000052228", "2000052229", "2000044819", "2000039931"]]

In [125]:
capital.head(20)

    2000026113  2000053837  2000052228  2000052229  2000044819  2000039931
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN         NaN
5          NaN         NaN         NaN         NaN         NaN         NaN
6          NaN         NaN         NaN         NaN         NaN         NaN
7          2.0         2.0         NaN         1.0         NaN         NaN
8          NaN         NaN         NaN         NaN         NaN         NaN
9          NaN         NaN         NaN         NaN         NaN         NaN
10         NaN         NaN         0.8         1.0         NaN         NaN
11         NaN         NaN         NaN         NaN         NaN         NaN
12         NaN         NaN         NaN         NaN         NaN         NaN
13         NaN         NaN         NaN         NaN         NaN         NaN
14         NaN         NaN         NaN         NaN         NaN         NaN
15         NaN         NaN         NaN         NaN         NaN         NaN
16         NaN         NaN         NaN         NaN         NaN         NaN
17         NaN         NaN         NaN         NaN         NaN         NaN
18         NaN         NaN         NaN         NaN         NaN         NaN
19         NaN         NaN         0.8         1.0         NaN         NaN

In [126]:
capital.describe()

,2000026113,2000053837,2000052228,2000052229,2000044819,2000039931
count,12831.000000,10577.000000,2.133000e+03,3482.0,335.0,789.000000
mean,1.088614,1.089912,8.000000e-01,1.0,1.0,501.882204
std,0.419725,0.426688,2.942781e-14,0.0,0.0,90.872793
min,0.000000,0.000000,8.000000e-01,1.0,1.0,55.972030
25%,1.000000,1.000000,8.000000e-01,1.0,1.0,456.481655
50%,1.000000,1.000000,8.000000e-01,1.0,1.0,515.991016
75%,1.000000,1.000000,8.000000e-01,1.0,1.0,561.524047
max,4.000000,4.000000,8.000000e-01,1.0,1.0,753.299958

In [209]:
# capital = A_train_df[["2000019464"]]

In [129]:
def create_app_install_usage_map(app_install_ids, app_usage_ids):
    """
    create mapping from app install ids to app usage ids, and vice versa.
    """
    install2usage_dict = dict()
    usage2install_dict = dict()
    for install_id, usage_id in zip(app_install_ids, app_usage_ids):
        install_id_str = str(install_id)
        usage_id_str = str(usage_id)
        install2usage_dict[install_id_str] = usage_id_str
        usage2install_dict[usage_id_str] = install_id_str
    return install2usage_dict, usage2install_dict

In [206]:
def get_corid2info_dict(orgid2info_dict, orgid2corid_dict):
    """
    """
    corid2info_dict = dict()
    for key, info in orgid2info_dict.items():
        corid2info_dict[orgid2corid_dict[key]] = info
    return corid2info_dict

In [131]:
app_install_df = pd.read_csv('../../../data/cell_manager/app.txt', header=None)
app_install_ids = [str(val) for val in app_install_df.iloc[0].values]
app_usage_ids = [str(val) for val in app_install_df.iloc[1].values]

In [136]:
len(app_install_ids), len(app_usage_ids)

(214, 214)

In [137]:
install2usage_dict, usage2install_dict = create_app_install_usage_map(app_install_ids, app_usage_ids)

In [140]:
# usage2install_dict

In [183]:
id_mean_v4_df = pd.read_csv('../../../data/cell_manager/ID_meaning_v4.csv')

In [184]:
id2desc_dict, id2type_dict = get_id2info_dicts(id_mean_v4_df)

In [187]:
id2type_dict

{'610120': nan,
 '61012004': nan,
 '61012005': nan,
 '61012020': nan,
 '61012021': nan,
 '2000000134': '人口属性',
 '2000000136': '人口属性',
 '2000019444': '健康',
 '2000019464': nan,
 '2000019469': '理财',
 '2000019493': '理财',
 '2000021475': '消费',
 '2000024892': '设备属性',
 '2000024893': '设备属性',
 '2000024894': '设备属性',
 '2000024895': '设备属性',
 '2000024897': '设备属性',
 '2000024898': '设备属性',
 '2000024899': '设备属性',
 '2000024900': '设备属性',
 '2000024901': nan,
 '2000026099': '设备属性',
 '2000026100': '设备属性',
 '2000026101': '设备属性',
 '2000026102': '设备属性',
 '2000026103': '设备属性',
 '2000026104': '设备属性',
 '2000026105': '人口属性',
 '2000026113': '资产',
 '2000026114': '人口属性',
 '2000026480': '人口属性',
 '2000026497': '人口属性',
 '2000026823': '理财',
 '2000027070': '自我成长，健康',
 '2000027071': 'wifi',
 '2000027072': '理财',
 '2000027073': '理财',
 '2000027078': '餐饮',
 '2000027096': 'wifi',
 '2000027111': 'wifi',
 '2000027115': '餐饮',
 '2000027125': '理财',
 '2000027151': nan,
 '2000027169': '消费',
 '2000027188': '餐饮',
 '2000027263': '自我成长',
 '2000027365': '餐饮',
 '2000027374': '餐饮',
 '2000027382': '餐饮',
 '2000027441': '贷款',
 '2000027447': '贷款',
 '2000027845': '消费',
 '2000027846': '理财',
 '2000027847': '汽车服务',
 '2000027849': '旅游出行',
 '2000027850': '商务',
 '2000027851': '娱乐',
 '2000027854': '通讯',
 '2000027856': nan,
 '2000027860': nan,
 '2000027861': '娱乐',
 '2000027862': '咨询',
 '2000027868': '消费',
 '2000027871': '社交，通讯',
 '2000027872': '实事',
 '2000027873': '社交',
 '2000027874': '社交',
 '2000027875': '社交',
 '2000027876': '消费',
 '2000027879': '消费',
 '2000027884': '理财',
 '2000027885': '理财',
 '2000027886': '理财',
 '2000027887': '理财',
 '2000027888': '理财',
 '2000027889': '理财',
 '2000027890': '理财',
 '2000027891': '理财',
 '2000027895': nan,
 '2000027896': '汽车服务',
 '2000027899': nan,
 '2000027901': '消费',
 '2000027902': '消费',
 '2000027910': '家庭',
 '2000027912': '旅游出行',
 '2000027913': '旅游出行',
 '2000027915': '旅游出行',
 '2000027918': '旅游出行',
 '2000027920': '旅游出行',
 '2000027927': '娱乐',
 '2000027928': '娱乐',
 '2000027929': '娱乐',
 '2000027942': nan,
 '2000027948': '通讯',
 '2000027951': '自我成长',
 '2000027953': '育儿，家庭',
 '2000027954': nan,
 '2000027960': nan,
 '2000027970': nan,
 '2000027972': nan,
 '2000027974': nan,
 '2000027981': '旅游出行',
 '2000027983': nan,
 '2000027993': '娱乐',
 '2000028010': '实事',
 '2000028021': '医疗',
 '2000028028': '餐饮',
 '2000028040': '消费',
 '2000028044': '社交',
 '2000028051': '汽车服务',
 '2000028052': '汽车服务',
 '2000028062': nan,
 '2000038128': nan,
 '2000039719': '消费',
 '2000039720': '理财',
 '2000039721': '汽车服务',
 '2000039723': '旅游出行',
 '2000039724': '商务',
 '2000039725': '娱乐',
 '2000039726': '娱乐',
 '2000039731': '自我成长',
 '2000039740': '餐饮',
 '2000039749': '消费',
 '2000039757': '理财',
 '2000039758': '理财',
 '2000039759': '理财',
 '2000039760': '理财',
 '2000039761': '理财',
 '2000039762': '理财',
 '2000039763': '理财',
 '2000039768': nan,
 '2000039769': '汽车服务',
 '2000039771': '汽车服务',
 '2000039788': '旅游出行',
 '2000039795': nan,
 '2000039799': '商务',
 '2000039815': nan,
 '2000039833': nan,
 '2000039837': '自我成长',
 '2000039854': '旅游出行',
 '2000039876': '娱乐',
 '2000039921': '汽车服务',
 '2000039922': '汽车服务',
 '2000039931': '资产',
 '2000039933': '设备属性',
 '2000040011': '人口属性',
 '2000044819': '资产',
 '2000045217': '人口属性',
 '2000045218': '人口属性',
 '2000051238': nan,
 '2000051239': nan,
 '2000051240': nan,
 '2000051268': nan,
 '2000051324': '旅游出行',
 '2000051325': '旅游出行',
 '2000052228': '资产',
 '2000052229': '资产',
 '2000053552': '设备属性',
 '2000053668': '贷款',
 '2000053669': '贷款',
 '2000053670': '贷款',
 '2000053672': '贷款',
 '2000053673': '娱乐',
 '2000053708': '娱乐',
 '2000053714': nan,
 '2000053715': nan,
 '2000053718': nan,
 '2000053719': '娱乐',
 '2000053720': nan,
 '2000053742': '高危',
 '2000053743': '高危',
 '2000053744': '高危',
 '2000053746': '高危',
 '2000053747': '高危',
 '2000053748': '高危',
 '2000053750': '高危',
 '2000053806': '设备属性',
 '2000053837': '资产',
 '2000054989': '社会属性',
 '2000054990': '社会属性',
 '2000055917': nan,
 '2000055919': nan,
 '2000055935': nan,
 '2000055979': '理财',
 '2000055995': nan,
 '2000055996': nan,
 '2000055997': nan,
 '2000055998': nan,
 '2000056001': nan,
 '2000056002': nan,
 '2000056003': nan,
 '2000056004': nan,
 '2000056008': nan,
 '2000056009': nan,
 '2000056010': nan,
 '2000056011': nan,
 '2000056014': nan,
 '2000056015': nan,
 '2000056016': nan,
 '2000056017': nan,
 '2000056120': nan,
 '2000062874': nan,
 '2000064725': nan,
 '2000064741': nan,
 '2000064998': '逾期类',
 '2000064999': '逾期类',
 '2000065000': '逾期类',
 '2000065339': '逾期类',
 '2000065001': '逾期类',
 '2000065004': '逾期类',
 '2000065005': '逾期类',
 '2000065022': '贷款行为',
 '2000065023': '贷款行为',
 '2000065264': '高危行为',
 '2000065265': '高危行为',
 '2000065267': '高危行为',
 '2000065268': '高危行为',
 '2000065391': nan,
 '2000065392': nan,
 '2000065393': nan,
 '2000065394': nan,
 '2000065395': nan,
 '2000065396': nan,
 '2000065397': nan,
 '2000065398': nan,
 '2000065399': nan,
 '2000065400': nan,
 '2000065401': nan,
 '2000065556': nan,
 '2000065559': '资产分属性',
 '2000065564': nan,
 '2000065567': nan,
 '2000065621': 'v2反欺诈分',
 '2000065813': '资产分属性',
 '2000065814': '资产分属性',
 '2000065815': nan,
 '2000065816': nan,
 '2000065840': 'v2反欺诈分',
 '2000065841': 'v2反欺诈分',
 '2000065842': 'v2反欺诈分',
 '2000065843': 'v2反欺诈分',
 '2000065844': 'v2反欺诈分',
 '2000065845': 'v2反欺诈分',
 '2000065850': '申请多头',
 '2000065851': '申请多头',
 '2000065852': '申请多头',
 '2000065864': '资产分属性',
 '2000065865': '资产分属性',
 '2000065871': '资产分属性',
 '2000065941': 'v3反欺诈分',
 '2000065942': 'v3反欺诈分',
 '2000666662': 'v3版反欺诈分底层特征',
 '8666610001': 'v3版反欺诈分底层特征',
 '8666710001': 'v3版反欺诈分底层特征',
 '8666810001': 'v3版反欺诈分底层特征',
 '8667110001': 'v3版反欺诈分底层特征',
 '8668610009': 'v3版反欺诈分底层特征',
 '8668610011': 'v3版反欺诈分底层特征',
 '8668610014': 'v3版反欺诈分底层特征'}

In [201]:
appinstall_id2desc_dict, appinstall_ids_list = get_id2desc_of_type(id2type1_dict, id2desc_dict, ['app 安装'])

2000027845 移动购物
2000027846 金融理财
2000027847 汽车服务
2000027849 旅游出行
2000027850 办公商务
2000027851 移动视频
2000027854 电话通讯
2000027856 主题美化
2000027860 智能设备
2000027861 手机游戏
2000027862 新闻资讯
2000027868 快递
2000027871 即时通信
2000027872 论坛贴吧
2000027873 社区交友
2000027874 微博社交
2000027875 婚恋交友
2000027876 综合电商
2000027879 跨境电商
2000027884 综合理财
2000027885 理财guess1
2000027886 网上银行
2000027887 支付结算
2000027888 网络彩票
2000027889 记账理财
2000027890 现金借贷app安装
2000027891 理财guess2
2000027895 违章查询安装
2000027896 汽车交易
2000027899 营业厅
2000027901 快递物流
2000027902 在线团购
2000027910 家政服务
2000027912 火车服务
2000027913 地图导航
2000027915 在线旅游
2000027918 旅行工具
2000027920 民宿短租
2000027927 在线视频
2000027928 聚合视频
2000027929 短视频
2000027942 照相机
2000027948 网络电话
2000027951 词典翻译
2000027953 学前教育
2000027954 K12教育
2000027960 手机壁纸
2000027970 安全服务
2000027972 输入法
2000027974 应用商店
2000027981 天气服务
2000027983 手电筒
2000027993 棋牌游戏
2000028010 综合资讯
2000028021 预约挂号
2000028028 团购餐饮
2000028040 快递
2000028044 职业社交
2000028051 二手车交易
2000028052 一手车交易

In [202]:
appinstall_ids_list

['2000027845',
 '2000027846',
 '2000027847',
 '2000027849',
 '2000027850',
 '2000027851',
 '2000027854',
 '2000027856',
 '2000027860',
 '2000027861',
 '2000027862',
 '2000027868',
 '2000027871',
 '2000027872',
 '2000027873',
 '2000027874',
 '2000027875',
 '2000027876',
 '2000027879',
 '2000027884',
 '2000027885',
 '2000027886',
 '2000027887',
 '2000027888',
 '2000027889',
 '2000027890',
 '2000027891',
 '2000027895',
 '2000027896',
 '2000027899',
 '2000027901',
 '2000027902',
 '2000027910',
 '2000027912',
 '2000027913',
 '2000027915',
 '2000027918',
 '2000027920',
 '2000027927',
 '2000027928',
 '2000027929',
 '2000027942',
 '2000027948',
 '2000027951',
 '2000027953',
 '2000027954',
 '2000027960',
 '2000027970',
 '2000027972',
 '2000027974',
 '2000027981',
 '2000027983',
 '2000027993',
 '2000028010',
 '2000028021',
 '2000028028',
 '2000028040',
 '2000028044',
 '2000028051',
 '2000028052']

In [203]:
appinstall_id2desc_dict

{'2000027845': '移动购物',
 '2000027846': '金融理财',
 '2000027847': '汽车服务',
 '2000027849': '旅游出行',
 '2000027850': '办公商务',
 '2000027851': '移动视频',
 '2000027854': '电话通讯',
 '2000027856': '主题美化',
 '2000027860': '智能设备',
 '2000027861': '手机游戏',
 '2000027862': '新闻资讯',
 '2000027868': '快递',
 '2000027871': '即时通信',
 '2000027872': '论坛贴吧',
 '2000027873': '社区交友',
 '2000027874': '微博社交',
 '2000027875': '婚恋交友',
 '2000027876': '综合电商',
 '2000027879': '跨境电商',
 '2000027884': '综合理财',
 '2000027885': '理财guess1',
 '2000027886': '网上银行',
 '2000027887': '支付结算',
 '2000027888': '网络彩票',
 '2000027889': '记账理财',
 '2000027890': '现金借贷app安装',
 '2000027891': '理财guess2',
 '2000027895': '违章查询安装',
 '2000027896': '汽车交易',
 '2000027899': '营业厅',
 '2000027901': '快递物流',
 '2000027902': '在线团购',
 '2000027910': '家政服务',
 '2000027912': '火车服务',
 '2000027913': '地图导航',
 '2000027915': '在线旅游',
 '2000027918': '旅行工具',
 '2000027920': '民宿短租',
 '2000027927': '在线视频',
 '2000027928': '聚合视频',
 '2000027929': '短视频',
 '2000027942': '照相机',
 '2000027948': '网络电话',
 '2000027951': '词典翻译',
 '2000027953': '学前教育',
 '2000027954': 'K12教育',
 '2000027960': '手机壁纸',
 '2000027970': '安全服务',
 '2000027972': '输入法',
 '2000027974': '应用商店',
 '2000027981': '天气服务',
 '2000027983': '手电筒',
 '2000027993': '棋牌游戏',
 '2000028010': '综合资讯',
 '2000028021': '预约挂号',
 '2000028028': '团购餐饮',
 '2000028040': '快递',
 '2000028044': '职业社交',
 '2000028051': '二手车交易',
 '2000028052': '一手车交易'}

In [207]:
app_usage2desc_dict = get_corid2info_dict(appinstall_id2desc_dict, install2usage_dict)

In [219]:
app_usage2desc_dict, len(app_usage2desc_dict)

({'2000039719': '移动购物',
  '2000039720': '金融理财',
  '2000039721': '汽车服务',
  '2000039723': '旅游出行',
  '2000039724': '办公商务',
  '2000039725': '移动视频',
  '2000039728': '电话通讯',
  '2000039730': '主题美化',
  '2000039734': '智能设备',
  '2000039735': '手机游戏',
  '2000039736': '新闻资讯',
  '2000039742': '快递',
  '2000039744': '即时通信',
  '2000039745': '论坛贴吧',
  '2000039746': '社区交友',
  '2000039747': '微博社交',
  '2000039748': '婚恋交友',
  '2000039749': '综合电商',
  '2000039752': '跨境电商',
  '2000039757': '综合理财',
  '2000039758': '理财guess1',
  '2000039759': '网上银行',
  '2000039760': '支付结算',
  '2000039761': '网络彩票',
  '2000039762': '记账理财',
  '2000039763': '现金借贷app安装',
  '2000039764': '理财guess2',
  '2000039768': '违章查询安装',
  '2000039769': '汽车交易',
  '2000039772': '营业厅',
  '2000039774': '快递物流',
  '2000039775': '在线团购',
  '2000039783': '家政服务',
  '2000039785': '火车服务',
  '2000039786': '地图导航',
  '2000039788': '在线旅游',
  '2000039791': '旅行工具',
  '2000039793': '民宿短租',
  '2000039800': '在线视频',
  '2000039801': '聚合视频',
  '2000039802': '短视频',
  '2000039815': '照相机',
  '2000039821': '网络电话',
  '2000039824': '词典翻译',
  '2000039826': '学前教育',
  '2000039827': 'K12教育',
  '2000039833': '手机壁纸',
  '2000039843': '安全服务',
  '2000039845': '输入法',
  '2000039847': '应用商店',
  '2000039854': '天气服务',
  '2000039856': '手电筒',
  '2000039866': '棋牌游戏',
  '2000039883': '综合资讯',
  '2000039894': '预约挂号',
  '2000039901': '团购餐饮',
  '2000039913': '快递',
  '2000039917': '职业社交',
  '2000039921': '二手车交易',
  '2000039922': '一手车交易'},
 60)

In [224]:
result = get_id2desc_of_type(id2type1_dict, id2desc_dict, ['app使用'])
appusage_id2desc_dict, appusage_id2type_dict, appusage_ids_list = result

2000039719 移动购物
2000039720 金融理财
2000039721 汽车服务
2000039723 旅游出行
2000039724 办公商务
2000039725 移动视频
2000039726 移动音乐
2000039731 数字阅读
2000039740 餐饮
2000039749 综合电商
2000039757 综合理财
2000039758 理财guess1
2000039759 网上银行
2000039760 支付结算
2000039761 网络彩票
2000039762 记账理财(使用)
2000039763 现金借贷app使用
2000039768 违章查询使用
2000039769 汽车交易(使用)
2000039771 汽车社区(使用)
2000039788 在线旅游
2000039795 云盘存储
2000039799 名片管理
2000039815 照相机
2000039833 手机壁纸
2000039837 电子书
2000039854 天气服务
2000039876 游戏平台
2000039921 二手车交易
2000039922 一手车交易

In [225]:
appusage_id2desc_dict, len(appusage_id2desc_dict)

({'2000039719': '移动购物',
  '2000039720': '金融理财',
  '2000039721': '汽车服务',
  '2000039723': '旅游出行',
  '2000039724': '办公商务',
  '2000039725': '移动视频',
  '2000039726': '移动音乐',
  '2000039731': '数字阅读',
  '2000039740': '餐饮',
  '2000039749': '综合电商',
  '2000039757': '综合理财',
  '2000039758': '理财guess1',
  '2000039759': '网上银行',
  '2000039760': '支付结算',
  '2000039761': '网络彩票',
  '2000039762': '记账理财(使用)',
  '2000039763': '现金借贷app使用',
  '2000039768': '违章查询使用',
  '2000039769': '汽车交易(使用)',
  '2000039771': '汽车社区(使用)',
  '2000039788': '在线旅游',
  '2000039795': '云盘存储',
  '2000039799': '名片管理',
  '2000039815': '照相机',
  '2000039833': '手机壁纸',
  '2000039837': '电子书',
  '2000039854': '天气服务',
  '2000039876': '游戏平台',
  '2000039921': '二手车交易',
  '2000039922': '一手车交易'},
 30)

In [226]:
app_usage2desc_dict.update(appusage_id2desc_dict)

In [227]:
app_usage2desc_dict, len(app_usage2desc_dict)

({'2000039719': '移动购物',
  '2000039720': '金融理财',
  '2000039721': '汽车服务',
  '2000039723': '旅游出行',
  '2000039724': '办公商务',
  '2000039725': '移动视频',
  '2000039728': '电话通讯',
  '2000039730': '主题美化',
  '2000039734': '智能设备',
  '2000039735': '手机游戏',
  '2000039736': '新闻资讯',
  '2000039742': '快递',
  '2000039744': '即时通信',
  '2000039745': '论坛贴吧',
  '2000039746': '社区交友',
  '2000039747': '微博社交',
  '2000039748': '婚恋交友',
  '2000039749': '综合电商',
  '2000039752': '跨境电商',
  '2000039757': '综合理财',
  '2000039758': '理财guess1',
  '2000039759': '网上银行',
  '2000039760': '支付结算',
  '2000039761': '网络彩票',
  '2000039762': '记账理财(使用)',
  '2000039763': '现金借贷app使用',
  '2000039764': '理财guess2',
  '2000039768': '违章查询使用',
  '2000039769': '汽车交易(使用)',
  '2000039772': '营业厅',
  '2000039774': '快递物流',
  '2000039775': '在线团购',
  '2000039783': '家政服务',
  '2000039785': '火车服务',
  '2000039786': '地图导航',
  '2000039788': '在线旅游',
  '2000039791': '旅行工具',
  '2000039793': '民宿短租',
  '2000039800': '在线视频',
  '2000039801': '聚合视频',
  '2000039802': '短视频',
  '2000039815': '照相机',
  '2000039821': '网络电话',
  '2000039824': '词典翻译',
  '2000039826': '学前教育',
  '2000039827': 'K12教育',
  '2000039833': '手机壁纸',
  '2000039843': '安全服务',
  '2000039845': '输入法',
  '2000039847': '应用商店',
  '2000039854': '天气服务',
  '2000039856': '手电筒',
  '2000039866': '棋牌游戏',
  '2000039883': '综合资讯',
  '2000039894': '预约挂号',
  '2000039901': '团购餐饮',
  '2000039913': '快递',
  '2000039917': '职业社交',
  '2000039921': '二手车交易',
  '2000039922': '一手车交易',
  '2000039726': '移动音乐',
  '2000039731': '数字阅读',
  '2000039740': '餐饮',
  '2000039771': '汽车社区(使用)',
  '2000039795': '云盘存储',
  '2000039799': '名片管理',
  '2000039837': '电子书',
  '2000039876': '游戏平台'},
 68)

In [228]:
asset_df = pd.read_csv('../../../data/cell_manager/asset.csv')

In [229]:
asset_df.shape

(177986, 12)

In [230]:
asset_df.head(20)

,2000065559,2000065865,2000065813,2000065814,2000065864,2000065871,2000026113,2000039931,2000052229,2000053837,2000052228,2000044819
0,0.2275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.4980,0.465524,0.3997,0.59,0.42,0.40,NaN,NaN,NaN,NaN,NaN,NaN
2,0.5720,0.383784,0.3112,0.50,0.39,0.32,NaN,NaN,NaN,NaN,NaN,NaN
3,0.3832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.6239,0.462994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.2162,0.415927,0.4921,0.42,0.19,0.50,NaN,NaN,NaN,NaN,NaN,NaN
6,0.3183,0.310435,0.3115,0.30,0.44,0.27,NaN,NaN,NaN,NaN,NaN,NaN
7,0.5092,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,NaN,NaN
8,0.6787,0.531447,NaN,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.5163,0.518953,0.5434,0.50,0.41,0.45,NaN,NaN,NaN,NaN,NaN,NaN
10,0.4112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.8,NaN
11,0.5707,0.517691,0.4648,0.59,0.41,0.50,NaN,NaN,NaN,NaN,NaN,NaN
12,0.4550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.3619,0.383539,0.4022,0.35,0.40,0.42,NaN,NaN,NaN,NaN,NaN,NaN
14,0.3265,0.353327,0.3076,0.50,0.45,0.33,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0.5776,0.463102,0.4316,0.41,0.41,0.44,NaN,NaN,NaN,NaN,NaN,NaN
17,0.4474,0.390992,0.3951,0.38,0.38,0.40,NaN,NaN,NaN,NaN,NaN,NaN
18,0.3455,0.451478,0.4469,0.53,0.41,0.41,NaN,NaN,NaN,NaN,NaN,NaN
19,0.3939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,0.8,NaN